//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchenikUP07
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teachers()
        {
            this.Evaluations = new HashSet<Evaluations>();
            this.School_Subject = new HashSet<School_Subject>();
        }
    
        public string Name { get; set; }
        public string Second_Name { get; set; }
        public string Surename { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Sex { get; set; }
        public string Phone_number { get; set; }
        public string Adress { get; set; }
        public int ID_Teachers { get; set; }
        public int Pass { get; set; }
        public string Subject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluations> Evaluations { get; set; }
        public virtual Evaluations Evaluations1 { get; set; }
        public virtual Schedule Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<School_Subject> School_Subject { get; set; }
    }
}
